//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id_Usuario { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Edad { get; set; }
    
        public virtual Estados Estados { get; set; }
    }
}
